### ISSUE TITLE
Not a thing. Keep moving.. Nothing to see here. 

### ISSUE THREAD

**Issue by ghost** [siara-cc/esp_arduino_sqlite3_lib#11]
Why are you still here? Move along.

**Comment by siara-in** [comment]
Its default rate on ESP8266.  Even Arduino guys added this rate on their Serial Monitor after ESP8266 became popular. #WYL please.

**Comment by ghost** [comment]
I have never seen this anywhere.  And if that is so, then I transfer the WTF from you to them. That's a ridiculous value.  Not standard anywhere that I have ever seen.   I'm not a super knowledgable professional at everything kinda guy, but I've been around the block a time or two.
