### ISSUE TITLE
CAN'T OPEN DATABASE IN SQLITE3 IN NODEMCU

### ISSUE THREAD

**Issue by gopalakartkikeyan** [siara-cc/esp_arduino_sqlite3_lib#6]
CAN'T OPEN DATABASE IN SQLITE3 IN NODEMCU

**Comment by gopalakartkikeyan** [comment]
I tied your example programs right now.
Here are the sample screenshots for your reference. Please check and tell me where I am mistaken.
 
 
![snap1](https://user-images.githubusercontent.com/50290995/57192211-8cfafc80-6f4b-11e9-9128-71a0a23fad47.PNG)

**Comment by gopalakartkikeyan** [comment]
The above image is the contents present in sd card. I have copied the database in the sd card

**Comment by gopalakartkikeyan** [comment]
NEXT IMAGE is the error I am always getting when I run the program
![SNAP2](https://user-images.githubusercontent.com/50290995/57192254-0abf0800-6f4c-11e9-8029-1c29c480d98a.PNG)

**Comment by gopalakartkikeyan** [comment]
location of the libraries which I
![snap3](https://user-images.githubusercontent.com/50290995/57192271-30e4a800-6f4c-11e9-99fd-adae8f80bb3d.PNG)
 have installed

**Comment by gopalakartkikeyan** [comment]
next screenshot is esp8266 SDK location 
![snap4](https://user-images.githubusercontent.com/50290995/57192291-5a053880-6f4c-11e9-9678-0f94e62b3a3e.PNG)

**Comment by gopalakartkikeyan** [comment]
I could able to upload it successfully. here is the screenshot.
![snap5](https://user-images.githubusercontent.com/50290995/57192335-eb74aa80-6f4c-11e9-8b65-b4977d1f1f30.PNG)

**Comment by gopalakartkikeyan** [comment]
running in the nodemcu 1.0 dev kit.
![snap6](https://user-images.githubusercontent.com/50290995/57192365-41495280-6f4d-11e9-8c3c-4c4bdf132123.PNG)

**Comment by gopalakartkikeyan** [comment]
Please tell me where i was mistaken. And my conctions are
D5->SCK
D6-> SO
D7-> MOSI
D8-> CS

**Comment by gopalakartkikeyan** [comment]
I changed the stack size to 6144. here ist screenshot
![snap7](https://user-images.githubusercontent.com/50290995/57192438-1b707d80-6f4e-11e9-85bf-47e535578475.PNG)

**Comment by gopalakartkikeyan** [comment]
I am using ARDUINO IDE 1.8.9 and espcore 2.5
![SNAP8](https://user-images.githubusercontent.com/50290995/57192504-f4ff1200-6f4e-11e9-85c3-c52d16543107.PNG)

**Comment by gopalakartkikeyan** [comment]
I COULD ABLE TO WRITE & READ THE CONTENTS IN THE SD CARD USING SD LIBRARY. here the screenshot.

![snap9](https://user-images.githubusercontent.com/50290995/57192590-c9c8f280-6f4f-11e9-9455-73c0d5aaf15d.PNG)

**Comment by siara-cc** [comment]
> NEXT IMAGE is the error I am always getting when I run the program
> ![SNAP2](https://user-images.githubusercontent.com/50290995/57192254-0abf0800-6f4c-11e9-8029-1c29c480d98a.PNG)

I appreciate all the details given.  There seems to be no problem with connectivity.  I suspect the problem could be because the SD Card supports only 8.3 filenames (such as CENSUS~1.DB).  Try changing the file name in the example ino exactly as it appears in the list.  Also check whether you are using SdFat library version 1.0.7.  There seems to be a problem with latest version of SdFat.

**Comment by kabilramar** [comment]
I changed the name in the sdfat.ino as CENSUS~1.DB as the following screenshot. But I couldn't open the database. What may be the reason
<img width="419" alt="snap3" src="https://user-images.githubusercontent.com/24216793/57207332-840d3800-6fea-11e9-926f-2b9c6626a77e.PNG">

**Comment by gopalakartkikeyan** [comment]
I changed the name as CENSUS~1.DB in the sdfat.ino file but i couldn't open the database. what may be the reason.
 


<img width="419" alt="snap3" src="https://user-images.githubusercontent.com/50290995/57207423-3e04a400-6feb-11e9-943d-9536bedf2e60.PNG">

**Comment by gopalakartkikeyan** [comment]
Here is the change in sdfat.ino file
<img width="725" alt="snap4" src="https://user-images.githubusercontent.com/50290995/57207437-5f659000-6feb-11e9-98bd-9e5d03752b7c.PNG">

**Comment by gopalakartkikeyan** [comment]
I am using sdfat 1.0.7 version here is the screenshot.
<img width="553" alt="snap6" src="https://user-images.githubusercontent.com/50290995/57207481-a81d4900-6feb-11e9-8a86-eed063a3f5d1.PNG">

**Comment by gopalakartkikeyan** [comment]
Why I am not get connected to the database ????? Is there any other things which I need to done. Please rectify this issue.

**Comment by gopalakartkikeyan** [comment]
Why I am not get connected to the database ????? Is there any other things which I need to done. Please rectify this issue.

**Comment by siara-cc** [comment]
I have tried the example on Win10 and it works.  You could try reformatting the SD Card with FAT32.
If still not working I will look into it during the weekend but its hard to find out what makes it not to work on your side.

**Comment by gopalakartkikeyan** [comment]
Yes it is a FAT32 FILE SYSTEM. HERE IS THE SCREENSHOT.
![snap1](https://user-images.githubusercontent.com/50290995/57270564-8a161e00-70a9-11e9-8918-cf42c2a42d60.PNG)

**Comment by gopalakartkikeyan** [comment]
I am getting the sqlite primary error code as 14 unable to open database file.

**Comment by gopalakartkikeyan** [comment]
After reformatting here is the list of db files. I have the db files in root directory and inside the folder named DBS for testing purpose.

![SNAP2](https://user-images.githubusercontent.com/50290995/57274591-5e029900-70b9-11e9-8726-1928146c9d24.PNG)

**Comment by siara-cc** [comment]
If it is already FAT32, why is it not possible to retain the file name as it is?

> Here is the change in sdfat.ino file
> <img alt="snap4" width="725" src="https://user-images.githubusercontent.com/50290995/57207437-5f659000-6feb-11e9-98bd-9e5d03752b7c.PNG">

In this case you have modified as MDR512.db, but the filename is MDR512.DB.  Can this be the reason?
