### ISSUE TITLE
I can not compile any example.

### ISSUE THREAD

**Issue by dejavy** [siara-cc/esp_arduino_sqlite3_lib#7]
exit status 1
Compilation error for NodeMCU 1.0 (ESP-12E Module).

/.../Arduino/libraries/esp_arduino_sqlite3_lib-master/src/shox96_0_2.cpp:221: undefined reference to `memchr '
collect2: error: ld returned 1 exit status

**Comment by siara-cc** [comment]
Please try with ESP8266 SDK for Arduino 2.5.0
