### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by vignesh13404387** [siara-cc/esp_arduino_sqlite3_lib#8]
Hello, I am using sqlite3 library in my program to store data on SD card using wemos D1 R1. When I compile the code it shows 60%of program storage space is used and the program throughs out of memory error.  When I searched the web it lead to add PRAGMA page_size 512.  I have no idea about where to add it. Please help.  Thankyou

**Comment by siara-cc** [comment]
To change page size follow http://sqlite.1065341.n5.nabble.com/How-to-modify-page-size-td87692.html

**Comment by vignesh13404387** [comment]
![program pragma](https://user-images.githubusercontent.com/26120749/60073164-4cdf1b80-973d-11e9-8ca3-db5b2d8b2ff7.png)

I uploaded this program 

![pragma error](https://user-images.githubusercontent.com/26120749/60073195-697b5380-973d-11e9-9a02-28535ebada06.png)

And this is the output

**Comment by vignesh13404387** [comment]
![program pragma](https://user-images.githubusercontent.com/26120749/60073294-a8a9a480-973d-11e9-840b-80eed53dac99.png)
I uploaded this program and below is my output any suggestions please
![pragma error](https://user-images.githubusercontent.com/26120749/60073328-c2e38280-973d-11e9-9b68-6da3011ead21.png)

**Comment by siara-cc** [comment]
Support of `PRAGMA` is disabled in the library.  Page size is 512 default when you create using this library.  So need not set it explicitly.  Even then need to set it before opening the DB.
Please check:
- Are all the examples running without error.
- Have you changed stack size in `cont.h` to 6144
- Send code giving error if possible.
